/*
  This file was automatically generated by Vite during project setup.
  It contains configuration settings for the Vite build tool used in this React project.
  Modify carefully only if you understand Vite configuration options.
  Official Vite documentation: https://vitejs.dev/config/
*/

import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vite.dev/config/
export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: [['babel-plugin-react-compiler']],
      },
    }),
  ],
  server: {
  watch: {
    usePolling: true,
    interval: 100,
  },
  host: true,
}
})
